### ISSUE TITLE
Support generic rest end point for notification

### ISSUE THREAD

**Issue by sachinkbansal** [cuebook/CueObserve#130]
### Discussed in https://github.com/cuebook/CueObserve/discussions/129

<div type='discussions-op-text'>

<sup>Originally posted by **pjpringle** August 30, 2021</sup>
Not everyone has slack especially in the work place environments.  Provide support to plug in rest calls to notify of anomalies. </div>

- [x] Image bytes included in response json

**Comment by sdepablos** [comment]
Maybe instead of a plug-in system, an easier solution would be to provide the possibility to configure a webhook. This way anything can be connected in a fast way with things like Zapier, Integromat...
