### ISSUE TITLE
Schedule Tasks more that or equal 6 are being struck lifetime in celery queue

### ISSUE THREAD

**Issue by itsmesrds** [cuebook/CueObserve#133]
**Describe the bug**
Cueobserve scheduled tasks are getting being struck in celery queue and not completing(No error is thrown) 

![image](https://user-images.githubusercontent.com/39127566/132780826-053b44ad-9944-4e01-83f9-ee8277e5abda.png)

**To Reproduce**

1. create 6 different anomalies definitions
2. create 5 min cron interval & wait for 5min to start the scheduled tasks

th0se tasks are not completing even after 1 day. 

for debugging, I have tried executing 5 scheduled tasks and 1 Scheduled task separately(different cron intervals), its is working fine, but when the scheduled tasks are 6 with same cron interval those got struck and didn't finish

**Expected behavior**
It should complete the 6 accepted tasks and pull the next tasks

Thanks

**Comment by learnisV2** [comment]
Am also facing the same issue, any prioritization for this ? this can be the one of the hard stoppers.

**Comment by sachinkbansal** [comment]
@itsmesrds @learnisV2 we'll try to reproduce and get back

**Comment by ankitkpandey** [comment]
Hi @itsmesrds @learnisV2 
Thank you for bringing this issue to our notice, I'm currently working on routing tasks via separate queues for celery and will push the changes shortly. That should resolve the issue.
