### ISSUE TITLE
Docker Network Mode and port mapping

### ISSUE THREAD

**Issue by adrien-ferrara** [cuebook/CueObserve#196]
**Is your feature request related to a problem? Please describe.**
The docker-compose files provided sets everything with network mode "host". For various reason this setting does not work in my environment. 

**Describe the solution you'd like**
* Capacity to use port mapping within the docker-compose files. 
* Capacity to use a Docker Swarm

**Comment by adrien-ferrara** [comment]
Hello,

Any news about that subject ? Is it possible ?

Thank you.

**Comment by vincue** [comment]
The issue is resolved, updated code can be found in [latest release](https://github.com/cuebook/cueobserve), please try again with updated [documentation](https://cueobserve.cuebook.ai/installation).
