### ISSUE TITLE
Support SQL Server Data Source

### ISSUE THREAD

**Issue by adam133** [cuebook/CueObserve#52]
**Is your feature request related to a problem? Please describe.**
I'd love to give CueObserve a try but our warehouse is currently in MS SQL Server.

**Describe the solution you'd like**
Add SQL Server as a supported data source.

**Additional context**
I'd be interested in making the necessary pull request, but I'd like some high level advice on what might be needed.

Is it as simple as adding the necessary sqlserver.py in https://github.com/cuebook/CueObserve/tree/main/api/dbConnections ?

**Comment by vikrantcue** [comment]
Yes @adam133 it should be simple enough. Please follow the following steps to add SQL Server support:
1. Add the SQL Server connection type in seed data here: https://github.com/cuebook/CueObserve/blob/main/api/seeddata/connectionType.json
2. Add the required params to connect with SQL Server here:
https://github.com/cuebook/CueObserve/blob/main/api/seeddata/connectionType.json
3. Add the necessary sqlserver.py in  https://github.com/cuebook/CueObserve/tree/main/api/dbConnections. You can connect to SQL Server using pandas so you don't need to add any additional drivers.

**Comment by adam133** [comment]
@vikrantcue Running into some issues getting a MSSQL driver configured - I always have trouble with Linux SQL Server drivers. I'm not sure what you mean by saying that pandas has them built in - as far as I can tell it still needs a compiled DBAPI for MSSQL of some kind to connect.

Additional modifications I found that are needed: 
- https://github.com/cuebook/CueObserve/blob/main/api/dbConnections/utils.py - limitSql needs to comply with SQL Server's "top N <query>" syntax instead of "<query> limit N".
- https://github.com/cuebook/CueObserve/blob/main/api/dbConnections/tests/test_utils_dbConnections.py - add a test for the SQL Server version of limitSql, and a test connection for SQL Server.
- https://github.com/cuebook/CueObserve/tree/main/ui/src/assets/img - need to add a sql server SVG.

I don't have any of that functioning yet, just wanted to post an update on my findings.

**Comment by vincue** [comment]
Hi @adam133, pandas has `read_sql` function to connect to various servers, please try [this](https://docs.microsoft.com/en-us/sql/machine-learning/data-exploration/python-dataframe-pandas?view=sql-server-ver15) for connecting MSSQL to pandas dataframe.

- > https://github.com/cuebook/CueObserve/blob/main/api/dbConnections/utils.py - limitSql needs to comply with SQL Server's "top N " syntax instead of " limit N"

    Yes, it needs to be considered, either by creating a separate function or changing the function where limiting keyword ("limit" or "top") can be passed as a parameter.

**Comment by sachinkbansal** [comment]
@adam133 a few others are asking for SQL Server support. Our team would be happy to pick this up, so that we can make it available in our next release.
