### ISSUE TITLE
Clickhouse as datasource support

### ISSUE THREAD

**Issue by Slach** [cuebook/CueObserve#53]
**Describe the solution you'd like**
I'd love to give CueObserve a try but our warehouse is currently in MS SQL Server.

**Describe the solution you'd like**
Add ClickHouse as a supported data source.

I will wait when https://github.com/cuebook/CueObserve/issues/52 will resolve and try to implements PR

**Comment by sachinkbansal** [comment]
We can use ClickHouse Playground to test this. Credentials at https://clickhouse.tech/docs/en/getting-started/playground/.

Sample Dataset SQL
```
select
  date_trunc('hour', date_add(day, date_diff(day, toDate('2014-03-23'), today()), EventTime)) as NewEventTime,
  RegionID,
  OS,
  count(1) as Hits
from hits_v1
GROUP BY
  date_trunc('hour', date_add(day, date_diff(day, toDate('2014-03-23'), today()), EventTime)), RegionID, OS
order by date_trunc('hour', date_add(day, date_diff(day, toDate('2014-03-23'), today()), EventTime))
```

**Comment by sachinkbansal** [comment]
@Slach #52 is now closed. Would you want to pick this up?

**Comment by Slach** [comment]
@sachinkbansal unfortunately, I don't have enough time to pick up this issue
could you share the link to commit or PR where your team implements #52?

**Comment by sachinkbansal** [comment]
here it is https://github.com/cuebook/CueObserve/pull/104
